### ISSUE TITLE
handle separators

### ISSUE THREAD

**Issue by SimonGreenhill** [SimonGreenhill/rcldf#27]
```json
                        "datatype": "string",
                        "propertyUrl": "http://cldf.clld.org/v1.0/terms.rdf#source",
                        "required": false,
                        "separator": ";",
                        "name": "Source"
```

**Comment by HedvigS** [comment]
@xrotwang suggested working in the package csvwr into rcldf. One of the advantages is that it can take a json and we can hand off interpretation of csvw dialects. We wouldn't need to re-invent the wheel, and it'd be a similar relationship between rcldf and csvwr as pycldf has to pycsvw.

I had a little play around with it, and I rather like it. I experimented in a fork with it, [here](https://github.com/HedvigS/rcldf/tree/use-csvwr)

If you switch to that branch, and try something like:

`test <- cldf(mdpath = "tests/testthat/examples/wals_1A_cldf/")

test$c$tables[[1]]$dataframe
`

`test` will be a list of 2. The first item is the object you used to get out of `cldf()`, I named it `o` for convenience. The second item is what `csvwr::read_cswr()` gives, I named it `c`.

I was thinking of continuing and modifying the script so that the c object looks like the o cldf object, i.e. extract the tables, type, resources etc out of the csvwr output. 

Before I do that, do you @SimonGreenhill in general like the idea of using csvwr?

**Comment by SimonGreenhill** [comment]
yes, we should switch to csvwr, it should be more robust.

**Comment by HedvigS** [comment]
Genau :)! And it ought to help with the reading of ParameterTable in grambank too I think. Good times all around :)

**Comment by HedvigS** [comment]
#37 is neat! I think it closes this issue, unless I've misunderstood the issue topic.

**Comment by SimonGreenhill** [comment]
No, this refers to separators in field columns e.g. there might be multiple sources for a given entry in ValueTable. This would be specified by "Simon2004;Hedvig2005". Ideally this would be parsed to ['Simon2004', 'Hedvig2005']. 

This [test](https://github.com/SimonGreenhill/rcldf/blob/main/tests/testthat/test_separators.R) shows the expected behavior.

csvwr doesn't handle separators, so either we need to do this or ask upstream.

**Comment by SimonGreenhill** [comment]
Made an issue upstream: https://github.com/Robsteranium/csvwr/issues/8

**Comment by HedvigS** [comment]
> No, this refers to separators in field columns e.g. there might be multiple sources for a given entry in ValueTable. This would be specified by "Simon2004;Hedvig2005". Ideally this would be parsed to ['Simon2004', 'Hedvig2005'].
> 
> This [test](https://github.com/SimonGreenhill/rcldf/blob/main/tests/testthat/test_separators.R) shows the expected behavior.
> 
> csvwr doesn't handle separators, so either we need to do this or ask upstream.

Aha, I see. Now I understand. [In Gramgaps, specifically for Source we handle it with str_split() and unnest() ](https://github.com/grambank/gramgaps/blob/7b3341addcfb9e04d5bfc908cbd9a14a7be3604e/03_Gramgaps_bibliography.R#L41). As far as I understand the CLDF-rendering of grambank, the Source field always uses semicolons even if the coders did not.

**Comment by HedvigS** [comment]
I understand the value of having this directly in csvwr, I hope it gets addressed there.

**Comment by Robsteranium** [comment]
Thanks for your interest in csvwr.

As per my comment in the upstream thread I agree it would make sense to implement this in csvwr but I personally won't have time to tackle this in the near future. Naturally I'd welcome contributions if you wanted to submit a PR.

I've dropped in here just like to warn that the semantic interpretation of `csvw:separator` mightn't be what you're expecting - I certainly found it counter-intuitive.

It essentially defines that the cell value is a list.

If it's a [multi-value literal](https://www.w3.org/TR/tabular-data-primer/#list-values) it get's interpreted as you might expect, you get two triples one for each source:

`:doc :source "Simon2004", "Hedvig2005" `

If it's a [multi-value resource](https://w3c.github.io/csvw/metadata/#example-12-table-with-compact-urls-and-micro-syntax) - i.e. you specify a `valueUrl` template like `http://example.net/id/source/{Source}` - then all the values are rendered in the same URI creating a single triple who's object is a composite resource:

`:doc :source <http://example.net/id/source/Simon2004,Hedvig2005>`

Since we're dealing here with citations that refer to other publications (resources not values) I imagine this is probably not what you want. For example if you reversed the order you'd get a different resource `<http://example.net/id/source/Hedvig2005,Simon2004>`  although I suspect most people would consider this pair of sources equivalent regardless of order.

This make sense for the use case in the spec (query parameters) but I certainly found it disappointing, not least because the interpretation differs between literals and resources.

If you don't want to have your interpretation diverge from the standard then it might be that you want to create another orthogonal table.

**Comment by xrotwang** [comment]
@Robsteranium CLDF interprets cswv data a bit more simplistically: It just skips the "expand valueUrl" part. When pondering whether to base CLDF on csvw or frictionless datapackages, the ability to attach semantics to columns via propertyUrls won over the simpler data reading model of datapackages.

**Comment by SimonGreenhill** [comment]
Given the different interpretations of `separator` discussed above, I've opted for a simple stop-gap measure to parse separators if people want to in the CLDF context:

```{r}
o <- cldf('...')
o <- separate(o)
```

Implemented in https://github.com/SimonGreenhill/rcldf/commit/6c7d173eba16c3ead76d2b0dfc0b222a1efff145
